<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head>
	<!-- Copyright 2009 eMeter Corporation. All Rights Reserved. -->
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $config['name']; ?> Guides - <?php echo $name; ?></title>

	<link href="styles.css" rel="stylesheet" media="screen" type="text/css" />	
</head>

<body>

<div id="nonFooter">
<div class="header-wrap">
	<div class="header">
		<h1><?php echo $config['name']; ?></h1>
	
		<ul class="nav">
			<li><a href="index.html">Home</a></li>
			<li class="index">
				<a href="#">Guides Index</a>
			</li>
		</ul>
		
		<div class="clearfix"></div>
	</div>
</div>

<div class="intro-wrap">
	<div class="intro">
		<div class="disclaimer">
			<div class="toc">
				<h3>Chapters</h3>
				<ol>
					<?php foreach ($toc as $chapter => $topics): ?>
					<li>
						<a href="#<?php echo strtolower(str_replace(' ', '-', preg_replace('/[^a-zA-Z0-9 -]/', '', $chapter)));  ?>"><?php echo $chapter; ?></a>
						<?php if (count($topics) > 0): ?>
						<ul>
							<?php foreach ($topics as $topic): ?>
							<li><a href="#<?php echo strtolower(str_replace(' ', '-', preg_replace('/[^a-zA-Z0-9 -]/', '', $topic)));  ?>"><?php echo $topic; ?></a></li>
							<?php endforeach; ?>
						</ul>
						<?php endif; ?>
					</li>
					<?php endforeach; ?>
				</ol>
			</div>
		</div>
		<h2><?php echo $name; ?></h2>
		<?php echo $header; ?>
	</div>
</div>

<div class="body">
	<div class="content">
		<?php echo $body ?>
	</div>
</div>
</div>

<div class="footer-wrap">
	<div class="footer">
		
		<div class="copyright">
			Copyright &copy; 2010 by Ian Selby
		</div>
		<div class="powered-by">
			Generated by <a href="#">Documentr</a>
		</div>
		
		<div class="clearfix"></div>
	</div>
</div>

</body>
</html>