<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">
<head>
	<!-- Copyright 2009 eMeter Corporation. All Rights Reserved. -->
	<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
	<title><?php echo $config['name']; ?></title>

	<link href="styles.css" rel="stylesheet" media="screen" type="text/css" />	
</head>

<body>

<div id="nonFooter">
<div class="header-wrap">
	<div class="header">
		<h1><?php echo $config['name']; ?></h1>
	
		<ul class="nav">
			<li><a href="index.html">Home</a></li>
			<li class="index">
				<a href="#">Guides Index</a>
			</li>
		</ul>
		
		<div class="clearfix"></div>
	</div>
</div>

<div class="intro-wrap">
	<div class="intro">
		<div class="disclaimer">
			<div class="ticket">
				Guides marked with this icon are currently works in progress.  They may contain incomplete (if any) information and even errors.  While they may contain information
				useful to you, it is important to know they could be inaccurate and will change.
			</div>
		</div>
		<h2><?php echo $config['name']; ?> guides</h2>
		<p><?php echo $config['introduction']; ?></p>
	</div>
</div>

<div class="body">
	<?php foreach ($index as $section => $guide): ?>
	<div class="section">
		<h3><?php echo $section ?></h3>
		
		<?php foreach ($guide as $guideName): ?>
		<?php $guideInfo = $guides[$guideName]; ?>
		<dl>
			<dt><a href="#"><?php echo $guideName; ?></a></dt>
			<?php if (isset($guideInfo['wip']) && $guideInfo['wip'] == true): ?>
			<dd class="ticket"><?php echo $guideInfo['description']; ?></dd>
			<?php else: ?>
			<dd><?php echo $guideInfo['description']; ?></dd>	
			<?php endif; ?>
		</dl>
		<?php endforeach; ?>
	</div>
	<?php endforeach; ?>
	
</div>
</div>

<div class="footer-wrap">
	<div class="footer">
		
		<div class="copyright">
			Copyright &copy; 2010 by Ian Selby
		</div>
		<div class="powered-by">
			Generated by <a href="#">Documentr</a>
		</div>
		
		<div class="clearfix"></div>
	</div>
</div>

</body>
