<div class="footer-wrap">
	<div class="footer">
		
		<div class="copyright">
			<?php echo $config['copyright_message']; ?>
		</div>
		<div class="powered-by">
			Generated by <a href="#">Documentr</a>
		</div>
		
		<div class="clearfix"></div>
	</div>
</div>